- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "youngbin0027/tomcat:latest"
      docker_host: tcp://192.168.56.104:2375
      tls: false
      validate_certs: false
      state: started
      ports:
      - "80:8080"
